from flask import Blueprint, render_template, send_file
from flask_login import login_required
from io import BytesIO

from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak
)

from models.scan_history import ScanHistory

from scanner.website_info import scan_website
from scanner.header_scan import scan_headers
from scanner.ssl_scan import scan_ssl
from scanner.technology_scan import detect_technology
from scanner.cookie_scan import scan_cookies

def add_page_number(canvas, doc):
    canvas.saveState()

    canvas.setFont("Helvetica-Bold", 9)
    canvas.setFillColor(colors.HexColor("#0F172A"))
    canvas.drawString(
        20 * mm,
        287 * mm,
        "CyberShield AI Enterprise Security Assessment Report"
    )

    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)

    canvas.drawString(
        20 * mm,
        10 * mm,
        "Generated by CyberShield AI"
    )

    canvas.drawRightString(
        190 * mm,
        10 * mm,
        f"Page {doc.page}"
    )

    canvas.restoreState()

reports = Blueprint("reports", __name__)


# ==========================
# Reports Page
# ==========================
@reports.route("/reports")
@login_required
def reports_page():

    scans = (
        ScanHistory.query
        .order_by(ScanHistory.scan_date.desc())
        .all()
    )

    return render_template(
        "reports.html",
        scans=scans
    )


# ==========================
# View Report
# ==========================
@reports.route("/view-report/<int:id>")
@login_required
def view_report(id):

    scan = ScanHistory.query.get_or_404(id)

    website_info = scan_website(scan.website)
    headers = scan_headers(scan.website)
    ssl_info = scan_ssl(scan.website)
    technologies = detect_technology(scan.website)
    cookies = scan_cookies(scan.website)
    # ---------------- Score Breakdown ----------------

    total_headers = len(headers)

    present_headers = sum(
        1 for value in headers.values()
        if value != "Missing"
    )

    header_score = int((present_headers / total_headers) * 100)

    ssl_score = 100 if ssl_info["status"] == "Valid" else 20

    secure_cookies = sum(
        1 for cookie in cookies
        if cookie["secure"] == "Yes"
    )

    cookie_score = int((secure_cookies / len(cookies)) * 100) if cookies else 0

    port_score = 60
    # ==========================
    # AI Analysis
    # ==========================

    ai_analysis = []

    # Analyze Security Headers
    for header, value in headers.items():

        if value == "Missing":
            ai_analysis.append(
                f"Security header '{header}' is missing. This increases the website's exposure to common web attacks."
            )

    # Analyze SSL
    if ssl_info["status"] == "Valid":

        ai_analysis.append(
            f"SSL certificate is valid and secured using {ssl_info['version']}."
        )

    else:

        ai_analysis.append(
            "SSL certificate is invalid or expired. Renew the certificate immediately."
        )

    # Analyze Cookies
    for cookie in cookies:

        if cookie["secure"] == "No":
            ai_analysis.append(
                f"Cookie '{cookie['name']}' is not marked Secure and may be transmitted over unsecured connections."
            )

    # Website Summary
    if scan.security_score >= 90:

        ai_analysis.append(
            "Overall website security posture is excellent with minimal risks detected."
        )


    elif scan.security_score >= 70:

        ai_analysis.append(
            "Website security is good but several improvements are recommended."
        )

    else:

        ai_analysis.append(
            "Website has multiple security weaknesses that should be addressed immediately."
        )

    # If nothing found
    if len(ai_analysis) == 0:
        ai_analysis.append(
            "No major security issues detected during this scan."
        )

    # ---------------- AI Recommendations ----------------

    ai_recommendations = []

    for header, value in headers.items():
        if value == "Missing":
            ai_recommendations.append(
                f"Add the '{header}' security header."
            )

    if ssl_info["status"] != "Valid":
        ai_recommendations.append(
            "Renew or replace the SSL certificate."
        )

    for cookie in cookies:
        if cookie["secure"] == "No":
            ai_recommendations.append(
                f"Mark cookie '{cookie['name']}' as Secure."
            )

    if not ai_recommendations:
        ai_recommendations.append(
            "Continue monitoring your website security regularly."
        )

    return render_template(
        "view_report.html",
        scan=scan,
        website_info=website_info,
        headers=headers,
        ssl_info=ssl_info,
        technologies=technologies,
        cookies=cookies,

        header_score = header_score,
        ssl_score = ssl_score,
        cookie_score = cookie_score,
        port_score = port_score,
        ai_analysis=ai_analysis,
        ai_recommendations=ai_recommendations
    )


# ==========================
# Download PDF
# ==========================
@reports.route("/download-report/<int:id>")
@login_required
def download_report(id):

    scan = ScanHistory.query.get_or_404(id)
    website_info = scan_website(scan.website)
    headers = scan_headers(scan.website)
    ssl_info = scan_ssl(scan.website)
    technologies = detect_technology(scan.website)
    cookies = scan_cookies(scan.website)
    buffer = BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    styles = getSampleStyleSheet()

    title = styles["Title"]
    title.alignment = TA_CENTER

    story = []

    # ===========================
    # ENTERPRISE COVER PAGE
    # ===========================

    enterprise_title = ParagraphStyle(
        "EnterpriseTitle",
        parent=styles["Title"],
        alignment=TA_CENTER,
        fontName="Helvetica-Bold",
        fontSize=28,
        textColor=colors.HexColor("#0F172A"),
        spaceAfter=10,
    )

    enterprise_sub = ParagraphStyle(
        "EnterpriseSub",
        parent=styles["Heading2"],
        alignment=TA_CENTER,
        fontName="Helvetica-Bold",
        fontSize=14,
        textColor=colors.HexColor("#2563EB"),
        spaceAfter=30,
    )

    story.append(Paragraph("CyberShield AI", enterprise_title))
    story.append(Paragraph("Enterprise Website Security Assessment Report", enterprise_sub))

    story.append(Spacer(1, 25))

    score = scan.security_score

    if score >= 90:
        grade = "A+"
        score_color = colors.HexColor("#22C55E")
    elif score >= 75:
        grade = "B+"
        score_color = colors.HexColor("#F59E0B")
    else:
        grade = "C"
        score_color = colors.HexColor("#EF4444")

    score_table = Table([
        ["SECURITY SCORE"],
        [f"{score}/100"],
        [grade]
    ], colWidths=[220])

    score_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), score_color),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.white),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 14),
        ("FONTSIZE", (0, 1), (-1, 1), 28),
        ("FONTSIZE", (0, 2), (-1, 2), 18),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 15),
    ]))

    story.append(score_table)

    story.append(Spacer(1, 25))

    summary = [

    ["Target Website", scan.website],

    ["Security Score", f"{scan.security_score}/100"],

    ["Risk Level", scan.risk_level],

    ["Report ID", f"CSA-{scan.id:06d}"],

    ["Generated", scan.scan_date.strftime("%d %B %Y %I:%M %p")],

    ["Generated By", "CyberShield AI"],

    ["Classification", "Confidential"]

]

    table = Table(summary, colWidths=[180, 300])

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#0F172A")),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
        ("BACKGROUND", (1, 0), (1, -1), colors.whitesmoke),
        ("GRID", (0, 0), (-1, -1), 1, colors.grey),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
    ]))

    story.append(table)

    story.append(PageBreak())

    # ===========================
    # EXECUTIVE SUMMARY
    # ===========================

    story.append(Paragraph(
        "Executive Summary",
        styles["Heading1"]
    ))

    story.append(Paragraph(
        f"""
        CyberShield AI completed a comprehensive security assessment of
        <b>{scan.website}</b>. The website received a
        <b>{scan.security_score}/100</b> security score with an overall
        <b>{scan.risk_level}</b> risk level.
        """,
        styles["BodyText"]
    ))

    story.append(Spacer(1, 20))

    # ===========================
    # WEBSITE INFORMATION
    # ===========================

    story.append(Paragraph(
        "1. Website Information",
        styles["Heading1"]
    ))

    website = [
        ["Parameter", "Value"],
        ["Target URL", scan.website],
        ["IP Address", website_info["ip_address"]],
        ["Web Server", website_info["server"]],
        ["HTTP Status", website_info["status_code"]],
        ["HTTPS Enabled", website_info["https"]],
        ["Response Time", f'{website_info["response_time"]} ms']
    ]

    table = Table(website, colWidths=[180, 300])

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0F172A")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

        ("BACKGROUND", (0, 1), (0, -1), colors.HexColor("#E2E8F0")),

        ("GRID", (0, 0), (-1, -1), 1, colors.HexColor("#CBD5E1")),

        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),

        ("ALIGN", (0, 0), (-1, -1), "CENTER"),

        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
    ]))

    story.append(table)

    story.append(Spacer(1, 25))

    # ===========================
    # SSL / TLS CERTIFICATE ASSESSMENT
    # ===========================

    story.append(Paragraph(
        "2. SSL / TLS Certificate Assessment",
        styles["Heading1"]
    ))

    ssl_table = [
        [
            "Certificate Status",
            "Issuer",
            "TLS Version",
            "Expiry Date"
        ],
        [
            ssl_info["status"],
            ssl_info["issuer"],
            ssl_info["version"],
            ssl_info["expires"]
        ]
    ]

    table = Table(
        ssl_table,
        colWidths=[120, 180, 100, 120]
    )

    table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0F172A")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

        ("GRID", (0, 0), (-1, -1), 1, colors.HexColor("#CBD5E1")),

        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

        ("ALIGN", (0, 0), (-1, -1), "CENTER"),

        ("BACKGROUND", (0, 1), (-1, 1), colors.whitesmoke),

        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),

    ]))

    story.append(table)

    story.append(Spacer(1, 20))

    # ===========================
    # SECURITY HEADERS
    # ===========================

    story.append(
        Paragraph(
            "3. Security Headers Assessment",
            styles["Heading1"]
        )
    )

    header_data = [
        ["Security Header", "Status"]
    ]

    for header, value in headers.items():
        status = "Present" if value else "Missing"

        header_data.append([
            header,
            status
        ])

    table = Table(
        header_data,
        colWidths=[280, 200]
    )

    table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0F172A")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

        ("GRID", (0, 0), (-1, -1), 1, colors.HexColor("#CBD5E1")),

        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

        ("ALIGN", (0, 0), (-1, -1), "CENTER"),

        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),

        ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke)

    ]))

    story.append(table)

    story.append(Spacer(1, 20))

    # ===========================
    # TECHNOLOGY STACK
    # ===========================

    story.append(
        Paragraph(
            "4. Technology Stack Detection",
            styles["Heading1"]
        )
    )

    tech_data = [
        ["Technology Detected"]
    ]

    for tech in technologies:
        tech_data.append([tech])

    table = Table(
        tech_data,
        colWidths=[480]
    )

    table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0F172A")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

        ("GRID", (0, 0), (-1, -1), 1, colors.HexColor("#CBD5E1")),

        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

        ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),

        ("ALIGN", (0, 0), (-1, -1), "CENTER")

    ]))

    story.append(table)

    story.append(Spacer(1, 20))

    # ===========================
    # COOKIE SECURITY ANALYSIS
    # ===========================

    story.append(
        Paragraph(
            "5. Cookie Security Assessment",
            styles["Heading1"]
        )
    )

    cookie_data = [
        ["Cookie", "Secure", "Domain"]
    ]

    for cookie in cookies:
        secure = "Yes" if cookie["secure"] else "No"

        cookie_data.append([
            cookie["name"],
            secure,
            cookie["domain"]
        ])

    table = Table(
        cookie_data,
        colWidths=[180, 80, 220]
    )

    table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0F172A")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

        ("GRID", (0, 0), (-1, -1), 1, colors.HexColor("#CBD5E1")),

        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

        ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

        ("ALIGN", (0, 0), (-1, -1), "CENTER"),

        ("BOTTOMPADDING", (0, 0), (-1, -1), 10)

    ]))

    story.append(table)

    story.append(Spacer(1, 20))

    # ===========================
    # SECURITY FINDINGS
    # ===========================

    story.append(
        Paragraph(
            "6. Security Findings & Recommendations",
            styles["Heading1"]
        )
    )

    findings = []

    if scan.security_score >= 90:
        findings.append([
            "🟢 LOW",
            "Excellent security posture. Continue monitoring and perform periodic security assessments."
        ])

    elif scan.security_score >= 75:
        findings.append([
            "🟡 MEDIUM",
            "Minor security improvements are recommended to strengthen the website."
        ])

    else:
        findings.append([
            "🔴 HIGH",
            "Immediate remediation is recommended. Several important security controls are missing."
        ])

    finding_table = [["Severity", "Recommendation"]]

    finding_table.extend(findings)

    table = Table(
        finding_table,
        colWidths=[100, 380]
    )

    table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0F172A")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

        ("GRID", (0, 0), (-1, -1), 1, colors.HexColor("#CBD5E1")),

        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

        ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

        ("VALIGN", (0, 0), (-1, -1), "TOP"),

        ("BOTTOMPADDING", (0, 0), (-1, -1), 10)

    ]))

    story.append(table)

    story.append(Spacer(1, 20))

    # ===========================
    # AI SECURITY ANALYSIS
    # ===========================

    story.append(
        Paragraph(
            "7. AI Security Analysis",
            styles["Heading1"]
        )
    )

    analysis = f"""
    <b>Overall Assessment</b><br/><br/>

    CyberShield AI completed a security assessment of
    <b>{scan.website}</b>.

    The website achieved a security score of
    <b>{scan.security_score}/100</b>
    with an overall risk level of
    <b>{scan.risk_level}</b>.

    SSL/TLS configuration, HTTP security headers,
    technology stack and cookie security were analysed.

    Continuous vulnerability assessments,
    security header implementation,
    software updates,
    and SSL certificate monitoring
    are recommended to maintain a strong security posture.
    """

    ai_box = Table([[Paragraph(analysis, styles["BodyText"])]])

    ai_box.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#EFF6FF")),
        ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#2563EB")),
        ("LEFTPADDING", (0, 0), (-1, -1), 15),
        ("RIGHTPADDING", (0, 0), (-1, -1), 15),
        ("TOPPADDING", (0, 0), (-1, -1), 15),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 15),
    ]))

    story.append(ai_box)

    story.append(Spacer(1, 25))

    # ===========================
    # FINAL ASSESSMENT
    # ===========================

    story.append(
        Paragraph(
            "Final Assessment",
            styles["Heading1"]
        )
    )

    final_table = Table([

        ["Overall Security Score", f"{scan.security_score}/100"],

        ["Risk Level", scan.risk_level],

        ["Assessment", "Website Successfully Analysed"],

        ["Generated By", "CyberShield AI"],

        ["Report Status", "Completed"],

        ["Recommendation", "Perform regular security scans to maintain compliance."]

    ], colWidths=[180, 300])

    final_table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#0F172A")),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.white),

        ("GRID", (0, 0), (-1, -1), 1, colors.HexColor("#CBD5E1")),

        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),

        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),

    ]))

    story.append(final_table)

    story.append(Spacer(1, 30))

    story.append(
        Paragraph(
            "<b>CyberShield AI Enterprise Security Assessment Report</b>",
            styles["Heading2"]
        )
    )

    story.append(
        Paragraph(
            "This report is generated automatically and is intended to assist security professionals in identifying potential security issues. It should be reviewed together with manual security testing for complete assessment.",
            styles["BodyText"]
        )
    )
    doc.build(
        story,
        onFirstPage=add_page_number,
        onLaterPages=add_page_number
    )

    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name=f"CyberShield_Report_{scan.id}.pdf",
        mimetype="application/pdf"
    )